name: Basic Workflow Check

# Trigger workflow saat push ke main branch atau PR dibuat
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-workflow:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Tes apakah workflow berjalan
      - name: Say Hello
        run: echo "🎉 GitHub Actions is working perfectly!"

      # Cek file di repository
      - name: List Files in Repository
        run: ls -la

      # Tambahkan pengecekan jika file tertentu belum ada
      - name: Check for package.json
        run: |
          if [ -f "package.json" ]; then
            echo "✅ package.json found."
          else
            echo "⚠️ package.json not found. Ready to add dependencies later."
          fi
