name: Basic Workflow Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "🎉 GitHub Actions is working perfectly!"

      - name: List Files in Repository
        run: ls -la

      - name: Check for package.json
        run: |
          if [ -f "package.json" ]; then
            echo "✅ package.json found."
          else
            echo "⚠️ package.json not found. Ready to add dependencies later."
          fi
